'use strict';
const $args = (m => /* c8 ignore start */ m.__esModule ? m.default : m /* c8 ignore stop */)(require('./args.js'));
const $arguments = (m => /* c8 ignore start */ m.__esModule ? m.default : m /* c8 ignore stop */)(require('./arguments.js'));
const $array = (m => /* c8 ignore start */ m.__esModule ? m.default : m /* c8 ignore stop */)(require('./array.js'));
const $context = (m => /* c8 ignore start */ m.__esModule ? m.default : m /* c8 ignore stop */)(require('./context.js'));
const $false = (m => /* c8 ignore start */ m.__esModule ? m.default : m /* c8 ignore stop */)(require('./false.js'));
const $freeze = (m => /* c8 ignore start */ m.__esModule ? m.default : m /* c8 ignore stop */)(require('./freeze.js'));
const $function = (m => /* c8 ignore start */ m.__esModule ? m.default : m /* c8 ignore stop */)(require('./function.js'));
const $identity = (m => /* c8 ignore start */ m.__esModule ? m.default : m /* c8 ignore stop */)(require('./identity.js'));
const $object = (m => /* c8 ignore start */ m.__esModule ? m.default : m /* c8 ignore stop */)(require('./object.js'));
const $string = (m => /* c8 ignore start */ m.__esModule ? m.default : m /* c8 ignore stop */)(require('./string.js'));
const $true = (m => /* c8 ignore start */ m.__esModule ? m.default : m /* c8 ignore stop */)(require('./true.js'));

exports.args = $args;
exports.arguments = $arguments;
exports.array = $array;
exports.context = $context;
exports.false = $false;
exports.freeze = $freeze;
exports.function = $function;
exports.identity = $identity;
exports.object = $object;
exports.string = $string;
exports.true = $true;
